"""Exact validation of the internal LMM fitter and its small-sample
inference against R.

tests/data/lmm_reference.json holds lmerTest/pbkrtest results
(Satterthwaite and Kenward-Roger SE/df/p, REML variance components) for
the shared datasets in tests/data/lmm_datasets/, generated by
tests/data/gen_lmm_datasets.py + tests/data/r_lmm_reference.R. Because
these methods are deterministic given data, the two implementations
must agree to numerical precision — this is a stronger contract than
the MCSE-level protocol cross-checks.
"""

import csv
import json
from pathlib import Path

import numpy as np
import pytest

from recoverlite.lmm import fit_reml, infer_contrast

DATA = Path(__file__).parent / "data"
REFERENCE = json.loads((DATA / "lmm_reference.json").read_text())

RTOL = 1e-4  # relative agreement with lmerTest / pbkrtest


def load(name):
    rows = list(csv.DictReader(open(DATA / "lmm_datasets" / f"{name}.csv")))
    y = np.array([float(r["y"]) for r in rows])
    z = np.array([float(r["treatment"]) for r in rows])
    g = np.array([r["cluster"] for r in rows])
    X = np.column_stack([np.ones(len(y)), z])
    return y, X, g


@pytest.mark.parametrize("name", sorted(REFERENCE))
def test_reml_variance_components_match_lme4(name):
    ref = REFERENCE[name]
    y, X, g = load(name)
    fit = fit_reml(y, X, g)
    assert fit.tau2 == pytest.approx(ref["tau2"], rel=1e-4, abs=1e-8)
    assert fit.sigma2 == pytest.approx(ref["sigma2"], rel=1e-6)
    assert fit.degenerate == bool(ref["singular"])


@pytest.mark.parametrize("name", sorted(REFERENCE))
@pytest.mark.parametrize("method,key", [("satterthwaite", "sat"),
                                        ("kenward_roger", "kr")])
def test_inference_matches_r(name, method, key):
    ref = REFERENCE[name]
    y, X, g = load(name)
    fit = fit_reml(y, X, g)
    G = len(np.unique(g))
    inf = infer_contrast(fit, y, X, 1, 0.05, method, fallback_df=G - 2)
    assert inf["estimate"] == pytest.approx(ref["estimate"], rel=1e-6)
    assert inf["se"] == pytest.approx(ref[key]["se"], rel=RTOL)
    assert inf["df"] == pytest.approx(ref[key]["df"], rel=RTOL)
    assert inf["p"] == pytest.approx(ref[key]["p"], rel=1e-3, abs=1e-10)


def test_kr_equals_satterthwaite_in_balanced_designs():
    """Known theory: in balanced cluster-randomized designs both reduce
    to the cluster-level analysis with G - 2 df."""
    y, X, g = load("balanced_16x30_icc05")
    fit = fit_reml(y, X, g)
    sat = infer_contrast(fit, y, X, 1, 0.05, "satterthwaite", 14)
    kr = infer_contrast(fit, y, X, 1, 0.05, "kenward_roger", 14)
    assert sat["df"] == pytest.approx(14.0, abs=1e-3)
    assert kr["df"] == pytest.approx(14.0, abs=1e-3)
    assert sat["se"] == pytest.approx(kr["se"], rel=1e-6)


def test_methods_diverge_when_unbalanced():
    """The unbalanced case is what separates the methods (and what the
    expected-vs-observed information distinction is about)."""
    y, X, g = load("unbalanced_12")
    fit = fit_reml(y, X, g)
    sat = infer_contrast(fit, y, X, 1, 0.05, "satterthwaite", 10)
    kr = infer_contrast(fit, y, X, 1, 0.05, "kenward_roger", 10)
    assert abs(sat["df"] - kr["df"]) > 1
